<a href="https://colab.research.google.com/github/overgroove/samsung_lecture/blob/main/00_ML_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Machine learning review**

## **1. Machine learning(머신러닝)의 정의**
- **데이터를 통해 컴퓨터를 학습시키는 방법론**  
- **인간이 규칙을 일일이 가르치는 대신, 시스템이 스스로 패턴을 찾아내는 방법론**

## **2. 파이썬 머신러닝 패키지 scikit-learn**
- 머신러닝 모델링을 위한 파이썬 오픈소스 패키지  
- 다양한 머신러닝 모델뿐 아니라 머신러닝 모델링을 위한 전처리 알고리즘, 평가지표, 운영 방법론을 제공한다.  
- [https://scikit-learn.org/stable](https://scikit-learn.org/stable/)

## **3. Machine learning 모델의 학습방법과 타겟데이터에 따른 구분**
**타겟데이터($y$)** 데이터의 존재 유무에 따라 **supervised leanring**(**지도학습**)과 **unsupervised**(**비지도 학습**)으로 구분하며 학습방법이 달라진다.

### 3.1 **supervised learning**(**지도학습**)
- ML모델이 결과값을 출력하기 위한 정답/target값 까지 함께 학습하는 학습방법  
- 모델을 학습시키기 위해 $y$값(target data, 정답, 레이블)이 반드시 필요  
- **supervied learning** 학습방법 내 $y$값의 분포에 따라 - **prediction**(**예측**), **classification**(**분류**) 문제로 구분 할 수 있습니다.

#### 3.1.1 **prediction**(**예측**) : target data의 분포가 **continuous distribution**(**연속형분포**)를 보일 때
 - 연속형분포 데이터 - 매출, 온도, 시간, 코스피지수, 가격 등  
 - 자연수 0과 1사이에는 무수히 많은 실수가 존재하고 그 무한한 값의 범위를 갖는 데이터를 연속형 데이터라 한다.(실수데이터)

<div align="center">
  <img src="https://raw.githubusercontent.com/overgroove/ML_lecture_image_data/main/image/02.png">
</div>

#### 3.1.2 **classification**(**분류**) : 종속변수가 **categorical distribution**(**범주형**)분포를 보일 때
* 범주형 데이터 - 성별, 신용등급, 브랜드, 기차역 등  
* 남성 혹은 여성 구분처럼 이진형 구분(0 혹은 1), 데이터가 특정 범위내에 모두 속한 데이터의 경우 범주형 데이터 혹은 카테고리 데이터라고 한다.

<div align="center">
  <img src="https://raw.githubusercontent.com/overgroove/ML_lecture_image_data/main/image/03.png">
</div>

**supervised learning은 학습과정에서 정답을 함께 전달하고 컴퓨터가 정답을 맞출 수 있도록 학습**   
**기존 학습 과정에 사용한 정답 데이터가 있기 때문에 모델 성능을 객관적으로 평가 가능**

## **4. ML 프로젝트의 기본 흐름**
머신러닝 프로젝트는 일반적으로 다음의 단계를 거칩니다.

1. **문제 정의**: 비즈니스 목표 설정 및 데이터 확인.

2. **데이터 수집 및 전처리**: 결측치 처리, 이상치 제거, 데이터 정규화.

3. **모델 선택 및 학습**: 알고리즘 선정 후 데이터를 통한 학습 진행.

4. **평가**: 테스트 데이터를 활용하여 모델의 성능 측정.

5. **배포 및 모니터링**: 실제 서비스에 적용 후 성능 유지보수.

#**5. ML modeling flow**
일반적인 ML 모델링 플로우를 따라가며 ML 모델의 학습과정 및 결과도출 과정을 익혀보겠습니다.

## **5.1 데이터셋 제작 및 확보**
머신러닝 모델링을 위해 확보한 데이터는 일반적으로 테이블 형태(행, 열)의 shape을 갖는 데이터가 되며 이를 데이터셋이라는 이름으로 부릅니다.
<div align="center">
  <img src="https://raw.githubusercontent.com/overgroove/ML_lecture_image_data/main/image/06.png" height="300px" width="400px">
</div>

In [3]:
# 필요모듈 import
# 데이터 import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score

- 분석 프로세스 예시를 위해 보스턴 주택가격 예측 데이터셋을 사용하겠습니다.  
- 보스턴 주택가격 예측을 위한 데이터로서 13개의 설명변수($X$)와 보스턴 집값($y$)로 구성되어 있는 데이터셋입니다.  
- 설명변수의 설명은 아래와 같습니다.  

<div align="center">

| 변수명 | 데이터정보 |
| :--- | :--- |
| CRIM | 마을 당 범죄율 |
| ZN | 25,000 평방피트 이상의 부지에 대한 주거용지 비율 |
| INDUS | 마을당 상업지구 비율 |
| CHAS | Charles River 인접 여부 |
| NOX | 질소산화물 농도 |
| RM | 주택 당 방 갯수 |
| AGE | 1940년 이전 건설 된 자가 점유 유닛 비율 |
| DIS | 보스턴 고용센터까지의 가중치 거리 |
| RAD | 고속도로 접근도 지수 |
| TAX | 10,000달러 당 재산세 |
| PTRATIO | 학생 대 교사 비율 |
| B | 마을별 흑인 비율 |
| LSTAT | 마을별 인구 당 저소득층 비율 |

In [4]:
# 보스턴 집값 데이터 로딩
# 강의 깃헙 페이지의 데이터 폴더 내 boston.csv파일을 경로로 사용합니다.
df = pd.read_csv("https://raw.githubusercontent.com/overgroove/ML_lecture_image_data/refs/heads/main/data/boston.csv")
df.head()

      CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT     y
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [6]:
# 데이터의 간략 정보 및 기초통계량 확인
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  y        506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB

             CRIM          ZN       INDUS  ...           B       LSTAT           y
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...  356.674032   12.653063   22.532806
std      8.601545   23.322453    6.860353  ...   91.294864    7.141062    9.197104
min      0.006320    0.000000    0.460000  ...    0.320000    1.730000    5.000000
25%      0.082045    0.000000    5.190000  ...  375.377500    6.950000   17.025000
50%      0.256510    0.000000    9.690000  ...  391.440000   11.360000   21.200000
75%      3.677083   12.500000   18.100000  ...  396.225000   16.955000   25.000000
max     88.976200  100.000000   27.740000  ...  396.900000   37.970000   50.000000

[8 rows x 14 columns]

## **5.2 타겟데이터($y$) 분리**
- supervised learning은 정답데이터를 함께 학습하는 머신러닝 학습방법  
- 정답 데이터가 학습에 사용하는 설명변수에 포함 되어 있다면 머신러닝 모델은 정답데이터를 참고하여 모델링을 하기에 문제가 있을 수 있다.  
- 위에서 확인한 보스턴주택 데이터셋은 데이터셋 내 정답데이터로 사용 할 '$y$'변수가 포함되어 있어 이를 다른 변수명으로 구분하여 할당한다.  

<div align="center">
  <img src="https://raw.githubusercontent.com/overgroove/ML_lecture_image_data/main/image/07.png" height="300px" width="400px">
<div/>

In [8]:
# X, y 분리
y = df['y']
X = df.drop('y', axis=1)
# X.head()
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: y, Length: 506, dtype: float64

## **5.3 train test split**
- supervided 머신러닝 모델이 데이터를 학습하는데 있어 가장 핵심적인 과정이다.  
- 머신러닝 모델의 목적은 현재 사내에 축적되어 있는 데이터를 예측/분류하는 목적이 아님   
- 모수에 해당하는 신규데이터에 대한 자동화를 ML모델로 구현함에 있다.  
- 그렇기에 과거 데이터인 기존 데이터로 학습한 ML모델의 검증을 위한 검증용 데이터인 test데이터셋을 구분하는 과정을 거친다.  

<div align="center">
<img src="https://raw.githubusercontent.com/overgroove/ML_lecture_image_data/main/image/08.png" height="300px" width="400px">

In [9]:
# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404,), (102,))

## **5.4 모델생성**

<div align="center">
  <img src="https://raw.githubusercontent.com/overgroove/ML_lecture_image_data/main/image/09.png" height="300px" width="700px">
</div>

In [10]:
# 모델 정의
model = LinearRegression()

## **5.5 모델학습**
- 지도학습의 경우 X_train데이터에 대한 정답지에 해당하는 y_train데이터를 함께 모델에 전달하는 방법으로 모델 학습을 수행한다.  

<div align="center">
  <img src="https://raw.githubusercontent.com/overgroove/ML_lecture_image_data/main/image/10.png" height="300px" width="700px">
</div>

In [11]:
# 모델 학습
model.fit(X_train, y_train)

LinearRegression()

## **5.6 모델 예측/분류 결과값 확인 및 모델 검증**
- 학습이 완료 된 모델은 모델이 학습한 결과값에 따라 예측/분류 결과값을 낼 수 있는 상태가 된다.  
- 학습이 완료 된 모델에 검증용 데이터로 구분해둔 test데이터셋의 정답데이터를 제외한 X_train데이터만을 전달 해 모델의 예측값인 y predicted data를 확인한다.  
- y predicted 출력 데이터의 정답데이터라 할 수 있는 y_test데이터를 우리는 갖고 있기에 이 두 데이터를 비교하여 모델을 객관적으로 평가 할 수 있다.  

<div align="center">
  <img src="https://raw.githubusercontent.com/overgroove/ML_lecture_image_data/main/image/11.png" height="300px" width="700px">
</div>

In [13]:
# 모델 예측값 확인
pred = model.predict(X_test)

In [14]:
# 모델 평가
print(f"RMSE : {root_mean_squared_error(y_test, pred)}")
print(f"R2 score : {r2_score(y_test, pred)}")

RMSE : 4.928602182665332
R2 score : 0.6687594935356326