<a href="https://colab.research.google.com/github/overgroove/samsung_lecture/blob/main/04_feature_eng_derived.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Derived feature**
- 데이터셋에 존재하는 변수를 활용하여 새로운 변수를 생성
- 기존 변수의 특징이 반영되지 않는 형태로 저장 되었을 경우
- 변수의 특징을 잘 설명할 수 있는(컴퓨터가 이해하기 편한) 파생변수 생성
- 데이터의 타입이나 특성/패턴 보다는 도메인에 따른 처리 필요

## **data loading**

In [1]:
# 필요모듈 import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_openml

pd.options.display.max_columns = 200
pd.options.display.max_rows = 200

In [4]:
# 데이터 로딩
data = fetch_openml('house_prices', as_frame=True)
df = data['frame']
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,'Wd Sdng','Wd Shng',None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## **1. Generate simple calculate**

In [13]:
# 주택 판매 당시 주택 연식 계산 'YrSold', 'YearBuilt'
# 시간데이터는 이후 발생한 시점 숫자가 항상 큽니다.
df.head()
df['Yrbe'] = df['YrSold'] - df['YearBuilt']

In [19]:
# 판다스 구조
for i in [1, 2, 3, 4]:
    print(i + 1)
# 브로드캐스팅
df['YrSold'] + 1

2
3
4
5

In [21]:
# 판매 전 마지막 리모델링 햇수 계산 'YrSold', 'YearRemodAdd'
df['YrRebe'] = df['YrSold'] - df['YearRemodAdd']

In [23]:
# 총 주거면적 계산 'GrLivArea', 'TotalBsmtSF'
df['TotalLivAre'] = df['GrLivArea'] + df['TotalBsmtSF']

In [27]:
# 차고 유무 'GarageArea'
(df['GarageArea'] == 0).sum()
df['Garage'] = df['GarageArea'] > 0

In [32]:
# 총 욕실 갯수 'FullBath', 'HalfBath', 'BsmtFullBath', 'BsmtHalfBath'
df['BathArea'] = df['FullBath'] + (df['HalfBath'] * 2)  + df['BsmtFullBath'] + (df['BsmtHalfBath'] * 2)

np.False_

In [36]:
# 벽난로의 전체적인 품질 및 갯수를 아우르는 파생변수 생성
# 0. 결측데이터 처리
df['Fireplaces'].isna().any()
# 1. 벽난로 품질 변수 결측 데이터 처리
df['FireplaceQu'] = df['FireplaceQu'].fillna(0)
# 2. 품질 변수의 정수화
value_dict = {
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1,
    0: 0
}
# 3. 파생변수 연산 및 생성
df['FireplaceQu'] = df['FireplaceQu'].map(value_dict)
df['TotalFireplacesQu'] = df['Fireplaces'] * df['FireplaceQu']

array([0, 'TA', 'Gd', 'Fa', 'Ex', 'Po'], dtype=object)

- 변수의 특징을 잘 살릴 수 있는 파생변수가 생성 되었다면 해당 파생변수를 생성하기 위해 사용한 피연산 변수는 삭제해도 좋음
- 변수의 특징이 비슷하다면 해당 변수들을 한데 아우를 수 있는 파생변수를 만든다면 다중공선성 문제도 해결 가능함

## **2. Generate interaction**
- 단순 증감 연산이 아닌 관계형 변수도 생성 가능
- 합차연산이 아닌 곱연산을 통해 변수간 관계에 해당하는 파생변수도 생성 가능
- interaction 변수의 경우 기존 변수의 특징과 다른 새로운 특징을 가지기에 피연산 변수를 삭제 하지 않는 경우가 많음
- 다항 회귀에 주로 사용

In [40]:
# 1층 주거면적의 quality OverallQual GrLivArea
# 결측데이터 확인 (결측없음)
(df['OverallQual'].isna().any())
(df['GrLivArea'].isna().any())
# 변수 값 확인(그대로 활용)
df['OverallQual']
# 연산적용 및 파생변수 생성
df['OverallQualGrLivArea'] = df['OverallQual'] * df['GrLivArea']

0       7
1       6
2       7
3       7
4       8
       ..
1455    6
1456    6
1457    7
1458    5
1459    5
Name: OverallQual, Length: 1460, dtype: int64

## **3. datetime 데이터 추출**

In [42]:
# datetime 데이터프레임 생성
df1 = pd.DataFrame(pd.date_range(start='2023-01-01 00:00:00', periods=50, freq='h'), columns=['datetime'])
df1['datetime']

0    2023-01-01 00:00:00
1    2023-01-01 01:00:00
2    2023-01-01 02:00:00
3    2023-01-01 03:00:00
4    2023-01-01 04:00:00
5    2023-01-01 05:00:00
6    2023-01-01 06:00:00
7    2023-01-01 07:00:00
8    2023-01-01 08:00:00
9    2023-01-01 09:00:00
10   2023-01-01 10:00:00
11   2023-01-01 11:00:00
12   2023-01-01 12:00:00
13   2023-01-01 13:00:00
14   2023-01-01 14:00:00
15   2023-01-01 15:00:00
16   2023-01-01 16:00:00
17   2023-01-01 17:00:00
18   2023-01-01 18:00:00
19   2023-01-01 19:00:00
20   2023-01-01 20:00:00
21   2023-01-01 21:00:00
22   2023-01-01 22:00:00
23   2023-01-01 23:00:00
24   2023-01-02 00:00:00
25   2023-01-02 01:00:00
26   2023-01-02 02:00:00
27   2023-01-02 03:00:00
28   2023-01-02 04:00:00
29   2023-01-02 05:00:00
30   2023-01-02 06:00:00
31   2023-01-02 07:00:00
32   2023-01-02 08:00:00
33   2023-01-02 09:00:00
34   2023-01-02 10:00:00
35   2023-01-02 11:00:00
36   2023-01-02 12:00:00
37   2023-01-02 13:00:00
38   2023-01-02 14:00:00
39   2023-01-02 15:00:00
40   2023-01-02 16:00:00
41   2023-01-02 17:00:00
42   2023-01-02 18:00:00
43   2023-01-02 19:00:00
44   2023-01-02 20:00:00
45   2023-01-02 21:00:00
46   2023-01-02 22:00:00
47   2023-01-02 23:00:00
48   2023-01-03 00:00:00
49   2023-01-03 01:00:00
Name: datetime, dtype: datetime64[ns]

In [43]:
# 시간차 계산
# 이후 발생 된 시간 숫자가 항상 큼
df1.loc[6, 'datetime'] - df1.loc[0, 'datetime']

Timedelta('0 days 06:00:00')

In [48]:
# 시간속성 분해
df1['year'] = df1['datetime'].dt.year
df1['month'] = df1['datetime'].dt.month
df1['day'] = df1['datetime'].dt.day
df1['hour'] = df1['datetime'].dt.hour
df1['minute'] = df1['datetime'].dt.minute
df1['second'] = df1['datetime'].dt.second
df1['microsecond'] = df1['datetime'].dt.microsecond
df1['weekday'] = df1['datetime'].dt.dayofweek # 월요일부터 0 카테고리컬 화 인코딩 추천
df1

,datetime,year,month,day,hour,minute,second,microsecond,weekday
0,2023-01-01 00:00:00,2023,1,1,0,0,0,0,6
1,2023-01-01 01:00:00,2023,1,1,1,0,0,0,6
2,2023-01-01 02:00:00,2023,1,1,2,0,0,0,6
3,2023-01-01 03:00:00,2023,1,1,3,0,0,0,6
4,2023-01-01 04:00:00,2023,1,1,4,0,0,0,6
5,2023-01-01 05:00:00,2023,1,1,5,0,0,0,6
6,2023-01-01 06:00:00,2023,1,1,6,0,0,0,6
7,2023-01-01 07:00:00,2023,1,1,7,0,0,0,6
8,2023-01-01 08:00:00,2023,1,1,8,0,0,0,6
9,2023-01-01 09:00:00,2023,1,1,9,0,0,0,6
10,2023-01-01 10:00:00,2023,1,1,10,0,0,0,6
11,2023-01-01 11:00:00,2023,1,1,11,0,0,0,6
12,2023-01-01 12:00:00,2023,1,1,12,0,0,0,6
13,2023-01-01 13:00:00,2023,1,1,13,0,0,0,6
14,2023-01-01 14:00:00,2023,1,1,14,0,0,0,6
15,2023-01-01 15:00:00,2023,1,1,15,0,0,0,6
16,2023-01-01 16:00:00,2023,1,1,16,0,0,0,6
17,2023-01-01 17:00:00,2023,1,1,17,0,0,0,6
18,2023-01-01 18:00:00,2023,1,1,18,0,0,0,6
19,2023-01-01 19:00:00,2023,1,1,19,0,0,0,6
20,2023-01-01 20:00:00,2023,1,1,20,0,0,0,6
21,2023-01-01 21:00:00,2023,1,1,21,0,0,0,6
22,2023-01-01 22:00:00,2023,1,1,22,0,0,0,6
23,2023-01-01 23:00:00,2023,1,1,23,0,0,0,6
24,2023-01-02 00:00:00,2023,1,2,0,0,0,0,0
25,2023-01-02 01:00:00,2023,1,2,1,0,0,0,0
26,2023-01-02 02:00:00,2023,1,2,2,0,0,0,0
27,2023-01-02 03:00:00,2023,1,2,3,0,0,0,0
28,2023-01-02 04:00:00,2023,1,2,4,0,0,0,0
29,2023-01-02 05:00:00,2023,1,2,5,0,0,0,0
30,2023-01-02 06:00:00,2023,1,2,6,0,0,0,0
31,2023-01-02 07:00:00,2023,1,2,7,0,0,0,0
32,2023-01-02 08:00:00,2023,1,2,8,0,0,0,0
33,2023-01-02 09:00:00,2023,1,2,9,0,0,0,0
34,2023-01-02 10:00:00,2023,1,2,10,0,0,0,0
35,2023-01-02 11:00:00,2023,1,2,11,0,0,0,0
36,2023-01-02 12:00:00,2023,1,2,12,0,0,0,0
37,2023-01-02 13:00:00,2023,1,2,13,0,0,0,0
38,2023-01-02 14:00:00,2023,1,2,14,0,0,0,0
39,2023-01-02 15:00:00,2023,1,2,15,0,0,0,0
40,2023-01-02 16:00:00,2023,1,2,16,0,0,0,0
41,2023-01-02 17:00:00,2023,1,2,17,0,0,0,0
42,2023-01-02 18:00:00,2023,1,2,18,0,0,0,0
43,2023-01-02 19:00:00,2023,1,2,19,0,0,0,0
44,2023-01-02 20:00:00,2023,1,2,20,0,0,0,0
45,2023-01-02 21:00:00,2023,1,2,21,0,0,0,0
46,2023-01-02 22:00:00,2023,1,2,22,0,0,0,0
47,2023-01-02 23:00:00,2023,1,2,23,0,0,0,0
48,2023-01-03 00:00:00,2023,1,3,0,0,0,0,1
49,2023-01-03 01:00:00,2023,1,3,1,0,0,0,1

## **4. Binning feature**
- 수치형 변수의 연속성이 넓게 퍼진 분포를 보일 경우 값을 치환하는 변수 생성
- 나이 --> 연령대 처럼 수치적 rank 보다는 구간에 맞춰 특성의 구조를 변경
- 수치형 --> 범주형 변환

In [50]:
# 주택 건설 년도 확인
df['YearBuilt'].min(), df['YearBuilt'].max()

(1872, 2010)

In [54]:
from pandas.core.reshape import encoding
# 구간화를 위한 sklearn.preprocessing KBinsDiscretizer
from sklearn.preprocessing import KBinsDiscretizer
kbins = KBinsDiscretizer(n_bins=10, encode='onehot-dense', strategy='quantile') # 몇구간? n_bins
kbins.fit(df[['YearBuilt']])
kbins.transform(df[['YearBuilt']])

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [52]:
# 구간 설정값 확인
kbins.bin_edges_

array([array([1872. , 1924.9, 1947.8, 1958. , 1965. , 1973. , 1984. , 1997.3,
              2003. , 2006. , 2010. ])                                       ],
      dtype=object)